# Linear Algebra for CpE
## Laboratory 8 : System of Linear Equations

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Coded and submitted by:<br>
Panelo, Bryan V.<br>
58011


### Exercise

1. Try to find your own example of a system of linear equations (minimum of 2 equations) and solve them using the inverse equation. Explain the details of your example.
2. Using your example in (1) solve it using `np.linalg.solve()`. Explain the function and its difference using the inverse equation.

<!-- <h1> Calculating the rate </h1>
Example: A dam is built in 1928 and the storage capacity of the dam is 300,000 acre-feet. In 1993, the townfolks determined that the buildup of sediment had reduced the resevoir's capacity to 189,000 acre-feet. Assuming the rate of sediment deposition has been constant  over that time period, at what rate(in acre-feet per year) is the reservoir's storage capacity being reduced?

##### use this formula

$$  r =\frac{d_2-d_1}{t_2-t_1}
$$     -->

So given an equation:
$$
Z = \left\{
    \begin{array}\\
        2x+5y=20\\ 
        3x+6y=18
    \end{array}
\right. $$

In [3]:
A = np.array([
    [2,5],
    [3,6]
])
B = np.array([
    [20],
    [18]
])

In [4]:
A_inv = np.linalg.inv(A)
A_inv

array([[-2.        ,  1.66666667],
       [ 1.        , -0.66666667]])

In [5]:
r = A_inv @ B
r

array([[-10.],
       [  8.]])

In [7]:
B_1 = A @ r
np.array_equal(B_1, B)
print(np.array_equal(B_1, B))
B_1


True


array([[20.],
       [18.]])

In [13]:
#using np.linalg.solve()

Solver = np.linalg.solve(A,B)
print("The answer is:", Solver)

The answer is: [[-10.]
 [  8.]]
